### ISSUE TITLE
Cannot recreate states in ROLLBACK_COMPLETE state

### ISSUE THREAD

**Issue by KierranM** [lethalpaga/cfncli#9]
### Given

I have a stack that has failed to create and is now in the `ROLLBACK_COMPLETE` state.
### When

I rerun `cfncli` with the same template.
### Then

I expect `CloudFormation` to attempt to recreate the stack.
### But

`cfncli` attempts to update the stack, which fails with the following message from CloudFormation:

```
stack_name is in ROLLBACK_COMPLETE state and can not be updated.
```

**Comment by KierranM** [comment]
Possible solution could involve adding an extra CLI option to automatically delete a stack if it exists and is in the `ROLLBACK_COMPLETE` state.

**Comment by lethalpaga** [comment]
Did your stack exist before failing? (i.e was it a stack creation or a stack update?).
CloudFormation cannot rollback a new stack as it has no previous state to go back to, and it ends in a red ROLLBACK_COMPLETE state. On an update though, it usually can go back to the previous state and end in a green ROLLBACK_COMPLETE that allow subsequent updates to be performed. AFAIK there is no way of differentiating a successful rollback from a failed one.

That's just how CloudFormation works and I don't think it's cfncli's responsibility to fix that. Your process could parse cfncli's output in case of error and try to delete and recreate the stack.

**Comment by KierranM** [comment]
The stack didn't exist. My understanding of CloudFormation is that when a stack rolls back during an update it finishes in the `UPDATE_ROLLBACK_COMPLETE` so it should be possible to differentiate between them. From what I could gather from the docs only new stacks that have failed can be in the `ROLLBACK_COMPLETE` state.

**Comment by KierranM** [comment]
2 years later I agree with @lethalpaga. Closing this issue
